airavata/urls.py
from __future__ import unicode_literals
import copy
import importlib
from django.core.exceptions import ImproperlyConfigured
from .utils import get_current_path
from .exceptions import NoRequestFound
from django.conf import settings


POLLA_PATCHED_RESOLVER = False

class UrlPatterns(object):

    def __init__(self, defaults=[]):
        if not settings.POLLA_REPLACE_DOTS_IN_DOMAINS:
            raise ImproperlyConfigured("POLLA_REPLACE_DOTS_IN_DOMAINS needs to be set to True in order to use this functionality")
        self.defaults = defaults
        self.extras = []

    def get_site_urls(self):
        try:
            current = get_current_path()
        except NoRequestFound:
            ## No request was found, falling back to defaults
            return None
        try:
            site_urls_module = importlib.import_module('sites.{}.urls'.format(current))
            patterns = getattr(site_urls_module, 'urlpatterns', None)
            return patterns
        except ImportError:
            pass
        except ValueError:
            pass
        return None

    def get_non_extra_urls(self):
        site_urls = self.get_site_urls()
        if site_urls is None:
            site_urls = copy.copy(self.defaults)
        return site_urls

    def get_current_urls(self):
        extras = copy.copy(self.extras)
        site_urls = self.get_non_extra_urls()
        site_urls.extend(extras)
        return site_urls

    def __iter__(self):
        return iter(self.get_current_urls())

    def __repr__(self):
        return '<{mod}.{cls}>'.format(
            mod=self.__class__.__module__,
            cls=self.__class__.__name__
        )

    def __str__(self):
        return '{}'.format(self.get_current_urls())

    __unicode__ = __str__

    def __contains__(self, other):
        if other in self.extras:
            return True
        urls = self.get_non_extra_urls()
        return other in urls

    def __len__(self):
        urls = self.get_current_urls()
        return len(urls)

    def __nonzero__(self):
        if len(self.extras):
            return True
        urls = self.get_non_extra_urls()
        return len(urls) > 0

    __bool__ = __nonzero__

    def __eq__(self, other):
        if self.defaults != other.defaults or self.extras != other.extras:
            return False
        return True

    def __add__(self, other):
        self.extras.extend(other)
        return self

    def __sub__(self, other):
        raise NotImplemented

    def __reversed__(self):
        to_reverse = list(self.get_current_urls())
        return reversed(to_reverse)

if not POLLA_PATCHED_RESOLVER:
    from .utils import get_resolver, get_ns_resolver
    from django.core import urlresolvers
    urlresolvers.get_resolver = get_resolver
    urlresolvers.get_ns_resolver = get_ns_resolver
    POLLA_PATCHED_RESOLVER = True

sites/example_com/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from test_app import urls as test_app_urls


urlpatterns = [
    url(r'^test/a\.html$', TemplateView.as_view(template_name='test_app/test-a.html'), name='test-a'),
    url(r'^test/b\.html$', TemplateView.as_view(template_name='test_app/test-b.html'), name='test-b'),
    url(r'', include(test_app_urls)),
]

test_app/urls.py
from django.conf.urls import url

from test_app.views import WhichSite, PageView


urlpatterns = [
    url(r'^$', WhichSite.as_view(), name='homepage'),
    url(r'^(?P<slug>[\w-]+)\.html$', PageView.as_view(), name='page'),
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from test_app import urls as test_app_urls
from airavata import urls


urlpatterns = urls.UrlPatterns([
    # Examples:
    # url(r'^$', 'airavata.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(test_app_urls)),
])

urlpatterns += [
    url(r'^' + settings.STATIC_URL[1:] + r'(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

airavata/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.sites.models import Site, _simple_domain_name_validator
from django.utils.translation import ugettext_lazy as _

from .utils import domain_available


@python_2_unicode_compatible
class SiteAlias(models.Model):

    site = models.ForeignKey(Site, verbose_name=_('site'), related_name='aliases')
    domain = models.CharField(_('domain name alias'), max_length=100, unique=True,
                              validators=[ _simple_domain_name_validator])

    class Meta:
        verbose_name = "SiteAlias"
        verbose_name_plural = "SiteAliases"

    def __str__(self):
        return '{} ({})'.format(self.domain, self.site.domain)

    def clean(self):
        domain_available(self, Site)
        super(SiteAlias, self).clean()

test_app/models.py
from django.db import models
from django.contrib.sites.models import Site


class Page(models.Model):

    site = models.ForeignKey(Site)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.title

airavata/views.py
from django.contrib.sites.shortcuts import get_current_site


class SiteFilteredViewMixin(object):

    site_field = 'site'

    def get_queryset(self):
        qs = super(SiteFilteredViewMixin, self).get_queryset()
        kwargs = {
          self.site_field: get_current_site(self.request),
        }
        return qs.filter(**kwargs)

test_app/views.py
from django.views.generic import DetailView, ListView
from django.views.generic.base import ContextMixin
from django.contrib.sites.shortcuts import get_current_site

from airavata.views import SiteFilteredViewMixin

from .models import Page


class PageListViewMixin(ContextMixin):

    def get_context_data(self, **kwargs):
        context = super(PageListViewMixin, self).get_context_data(**kwargs)
        context['site_pages'] = Page.objects.filter(site=get_current_site(self.request))
        return context


class PageView(SiteFilteredViewMixin, PageListViewMixin, DetailView):

    template_name = 'test_app/page.html'
    model = Page


class WhichSite(PageListViewMixin, ListView):

    template_name = 'test_app/which.html'
    model = Page

    def get_context_data(self, **kwargs):
        context = super(WhichSite, self).get_context_data(**kwargs)
        context['current_site'] = get_current_site(self.request)
        return context

sites/example_com/templates/base.html
{% load sitestatic %}
<html>
  <link rel="stylesheet" href="{% static 'css/site.css' %}">
  <body>
    <h1>CustomTemplate</h1>
    <ul style="list-style-type: none;">
      <li style="display: inline-block;"><a href="{% url 'homepage' %}">Home</a></li>
      {% for page in site_pages %}
        <li style="display: inline-block;" class="page"><a href="{% url 'page' page.slug %}">{{page.title}}</a></li>
      {% endfor %}
    </ul>
    <hr/>
    {% block content %}
    {% endblock content %}
  </body>
</html>  

test_app/templates/base.html
{% load sitestatic %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
  </head>
  <body>
    <ul style="list-style-type: none;">
      <li style="display: inline-block;"><a href="{% url 'homepage' %}">Home</a></li>
      {% for page in site_pages %}
        <li style="display: inline-block;" class="page"><a href="{% url 'page' page.slug %}">{{page.title}}</a></li>
      {% endfor %}
    </ul>
    <hr/>
    {% block content %}
    {% endblock content %}
  </body>
</html>  

test_app/templates/test_app/page.html
{% extends "base.html" %}

{% block content %}
  <h1>{{page.title}}</h1>
  {{page.body|safe}}
  <hr/>
  <small>Page id is: <span class="page_id">{{page.pk}}</span></small>
{% endblock content %}

test_app/templates/test_app/test-a.html
<html>
  <body>
    <h1>Test A</h1>
  </body>
</html>

test_app/templates/test_app/test-b.html
<html>
  <body>
    <h1>Test B</h1>
  </body>
</html>

test_app/templates/test_app/which.html
{% extends "base.html" %}

{% block content %}
  <p>Current site is:</p>
  <ul>
    <li>Domain: {{ current_site.domain }}</li>
    <li>ID: <span class="site_id">{{current_site.pk}}</span></li>
  </ul>
  <hr/>
  <p>Pages on this site:</p>
  <ul>
    {% for page in page_list %}
        <li>{{page.title}}</li>
    {% endfor %}
  </ul>
{% endblock content %}